### ISSUE TITLE
[CY-4171] Unknown option -o / Does the binary work?

### ISSUE THREAD

**Issue by NorseGaud** [codacy/codacy-faux-pas#12]
Newbie here and I'm a bit confused about how to use this. I curled the binary down and it doesn't seem like it works:

```
bash-4.2# ./codacy-faux-pas-0.1.4 -o json check ...
Error: Unknown option -o
Error: Unknown argument 'json'
Error: Unknown argument 'check'
Error: Unknown argument 'test'
Usage: faux-pas [options]

  -e, --encoding <value>  input encoding (default: UTF-8)
```

**Comment by josemiguelmelo** [comment]
Hi @NorseGaud 🙂

Our tool is a converter that receives Faux Pas' output as input and converts its format to Codacy's format. 
From the logs you attached, you're passing Faux Pas arguments to our tool which seems you're trying to run our tool as a wrapper of Faux Pas instead of a results converter.

You can find [here](https://github.com/codacy/codacy-faux-pas#sending-the-results-to-codacy) the detailed steps on how to use our tool and send results to Codacy.

Thank you,
